In [1]:
%matplotlib inline
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import glob

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
def SparkLogToDataFrame(filename):
    import json
    import pandas
    import numpy as np

    columns=['StageID','TaskId','ExecutorID','LaunchTime','SchedulerDelay','DeserializeTime','Runtime','GettingResultTime','ResultSerializationTime','FinishTime','ResultSize']

    stat_file=open(filename)
    stats=list();
    for line in stat_file:
        stats.append(json.loads(line))

      
        
        
    data=pandas.DataFrame(columns=columns,dtype=np.int64)
    data_point = np.zeros((1,11),dtype=np.int64)
    for stat in stats:
        if stat['Event'] == 'SparkListenerTaskEnd':
            data_point[0,0] = int(stat['Stage ID'])
            data_point[0,1] = int(stat['Task Info']['Task ID'])
            data_point[0,2] = int(stat['Task Info']['Executor ID'])
            data_point[0,3] = int(stat['Task Info']['Launch Time'])
            data_point[0,5] = int(stat['Task Metrics']['Executor Deserialize Time'])
            data_point[0,6] = int(stat['Task Metrics']['Executor Run Time'])
            data_point[0,7] = int(stat['Task Info']['Finish Time'])-int(stat['Task Info']['Getting Result Time']) if int(stat['Task Info']['Getting Result Time'])!=0 else 0 
            data_point[0,8] = int(stat['Task Metrics']['Result Serialization Time'])
            data_point[0,9] = int(stat['Task Info']['Finish Time'])
            data_point[0,10] = int(stat['Task Metrics']['Result Size'])
            
            data_point[0,4]= data_point[0,9]-data_point[0,3]-data_point[0,5]-data_point[0,6]-data_point[0,8]-data_point[0,7]
            data_case = pandas.DataFrame(data_point,columns=columns)
            data = data.append(data_case,ignore_index=True)
            
    return data

In [11]:
folders = glob.glob('Spark/iter2/*/app-*')
plotting_df = pd.DataFrame(columns=['Nodes','Time'])
for name in folders:
    df = SparkLogToDataFrame(name)
    time = df['FinishTime'].max()-df['LaunchTime'].min()
    node = int(name.split('/')[2].split('node')[0])
    plotting_df.loc[len(plotting_df)]=[node,time]

In [17]:
times_spark_mean = pd.DataFrame(columns=['Processes','Time'])
times_spark_mean.loc[0] = plotting_df[0:5].mean().values
times_spark_mean.loc[1] = plotting_df[5:10].mean().values
times_spark_mean.loc[2] = plotting_df[10:15].mean().values
times_spark_mean.loc[3] = plotting_df[15:20].mean().values
times_spark_mean.loc[4] = plotting_df[20:25].mean().values
times_spark_mean.loc[5] = plotting_df[25:30].mean().values
times_spark_mean['Std'] = [plotting_df['Time'][0:5].std()]

ValueError: Length of values does not match length of index

In [7]:
df

,StageID,TaskId,ExecutorID,LaunchTime,SchedulerDelay,DeserializeTime,Runtime,GettingResultTime,ResultSerializationTime,FinishTime,ResultSize
167,0,121,3,1507840107596,50,295,18333,0,1,1507840126275,241872
166,0,133,3,1507840107597,52,291,18321,0,1,1507840126262,241872
165,0,143,3,1507840107597,57,287,18266,0,0,1507840126207,241829
164,0,154,2,1507840107599,52,273,18263,0,0,1507840126187,241829
163,0,163,2,1507840107600,55,269,18246,0,0,1507840126170,241829
161,0,159,2,1507840107600,53,270,18219,0,1,1507840126143,241872
162,0,140,3,1507840107597,55,288,18214,0,0,1507840126154,241829
159,0,165,2,1507840107600,55,269,18185,0,0,1507840126109,242319
160,0,122,3,1507840107596,50,294,18181,0,0,1507840126121,241829
158,0,162,2,1507840107600,54,270,18163,0,0,1507840126087,241829
157,0,139,3,1507840107597,54,288,18097,0,0,1507840126036,241829
156,0,131,3,1507840107597,50,292,18065,0,1,1507840126005,241872
155,0,166,2,1507840107600,55,269,18007,0,0,1507840125931,241829
154,0,161,2,1507840107600,53,270,17964,0,1,1507840125888,241872
153,0,136,3,1507840107597,52,290,17899,0,1,1507840125839,241872
152,0,123,3,1507840107596,49,294,17880,0,1,1507840125820,241872
151,0,129,3,1507840107597,50,292,17824,0,0,1507840125763,241829
150,0,145,2,1507840107599,50,274,17730,0,1,1507840125654,241872
149,0,124,3,1507840107596,49,294,17690,0,1,1507840125630,241872
148,0,142,3,1507840107597,56,288,17676,0,0,1507840125617,241829
147,0,150,2,1507840107599,50,274,17605,0,1,1507840125529,241872
145,0,155,2,1507840107599,52,272,17586,0,1,1507840125510,241872
146,0,128,3,1507840107596,51,293,17576,0,1,1507840125517,241872
144,0,158,2,1507840107600,52,271,17558,0,1,1507840125482,241872
143,0,138,3,1507840107597,54,289,17540,0,0,1507840125480,241829
142,0,164,2,1507840107600,54,269,17529,0,1,1507840125453,241872
141,0,141,3,1507840107597,54,288,17413,0,0,1507840125352,241829
140,0,126,3,1507840107596,49,294,17362,0,0,1507840125301,241829
139,0,146,2,1507840107599,50,274,17307,0,1,1507840125231,241872
137,0,81,1,1507840107579,50,271,17108,0,1,1507840125009,241872
...,...,...,...,...,...,...,...,...,...,...,...
32,0,114,0,1507840107591,60,279,13035,0,1,1507840120966,241872
26,0,13,6,1507840107470,62,269,12846,0,0,1507840120647,241829
28,0,32,5,1507840107528,53,288,12813,0,0,1507840120682,241829
25,0,7,6,1507840107470,60,271,12751,0,0,1507840120552,241829
27,0,127,3,1507840107596,51,294,12710,0,0,1507840120651,241829
24,0,99,0,1507840107589,58,283,12616,0,0,1507840120546,241829
22,0,4,6,1507840107469,62,271,12455,0,0,1507840120257,241829
23,0,48,4,1507840107530,59,288,12402,0,1,1507840120280,241872
21,0,68,4,1507840107532,64,282,12364,0,0,1507840120242,241829
20,0,111,0,1507840107590,61,279,12082,0,0,1507840120012,241829
19,0,130,3,1507840107597,53,293,12067,0,1,1507840120011,241872
18,0,112,0,1507840107590,61,279,11879,0,0,1507840119809,241829
17,0,45,5,1507840107529,58,283,11823,0,1,1507840119694,241872
15,0,0,6,1507840107469,61,271,11811,0,0,1507840119612,241829
16,0,56,4,1507840107531,59,288,11791,0,0,1507840119669,241829
13,0,27,5,1507840107528,54,287,11580,0,0,1507840119449,241829
14,0,77,1,1507840107579,52,269,11580,0,0,1507840119480,241829
12,0,102,0,1507840107590,57,283,11461,0,0,1507840119391,241829
11,0,55,4,1507840107531,60,289,11389,0,0,1507840119269,241829
9,0,20,6,1507840107470,65,268,11299,0,0,1507840119102,241829
10,0,149,2,1507840107599,52,274,11188,0,0,1507840119113,241829
8,0,117,0,1507840107591,62,276,11075,0,0,1507840119004,241829
7,0,47,5,1507840107529,59,282,10420,0,0,1507840118290,241829
6,0,33,5,1507840107528,64,287,10248,0,1,1507840118128,241872
4,0,17,6,1507840107470,74,268,10025,0,1,1507840117838,241872
5,0,110,0,1507840107590,71,279,9999,0,1,1507840117940,241872
3,0,95,1,1507840107581,65,266,9691,0,1,1507840117604,241872
1,0,61,4,1507840107532,63,285,9658,0,1,1507840117539,241872
2,0,153,2,1507840107599,64,273,9622,0,0,1507840117558,241829
0,0,65,4,1507840107532,74,284,8677,0,1,1507840116568,241872